site_name: 逻辑与形而上学
site_author: 一之江
site_url: https://shiinahiiragi.github.io/note/
repo_url: https://github.com/ShiinaHiiragi/note/
repo_name: ShiinaHiiragi/note
dev_addr: 127.0.0.1:80
theme:
  name: material
  icon:
    logo: octicons/note-24
  favicon: extra/favicon.png
  features:
    - navigation.expand
    - navigation.tabs
  palette:
    accent: pink
  language: 'zh'

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ShiinaHiiragi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ShiinaHiiragi
  search:
    language: 'jp'

extra_javascript:
  - extra/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - extra/config.css

nav:
  - 通用:
    - 介绍: index.md
    # - 索引: intro/dir.md
    - 许可证: intro/license.md
  - 认识基础:
    - 二、形式逻辑:
      - 1 概念: cogn/formal/concept.md
      - 2 命题与演绎: cogn/formal/deduction.md
      - 3 归纳和类比: cogn/formal/induction.md
      - 4 非形式逻辑: cogn/formal/proof.md
  - 形而上学:
    - 三、数学哲学:
      - 1 基本问题与历史观点: meta/math/concept.md
      - 2 三大主义: meta/math/doctrine.md
      - 3 当代观点: meta/math/contemp.md
  - 数理逻辑:
    - 二、公理集合论:
      - 1 ZFC 集合论: logic/set/zfc.md
      - 2 关系与映射: logic/set/relation.md
      - 3 实数理论: logic/set/real.md
      - 4 序数: logic/set/ordinal.md
      - 5 势与基数: logic/set/cardinal.md
    - 三、模型论:
      - 1 结构与模型: logic/model/model.md
  - 数学结构:
    - 二、点集拓扑:
      - 1 拓扑空间: math/top/space.md
