site_name: 逻辑与形而上学
site_author: 一之江
site_url: https://shiinahiiragi.github.io/note/
repo_name: ShiinaHiiragi/note
repo_url: https://github.com/ShiinaHiiragi/note/
dev_addr: 127.0.0.1:3000

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: blue
      font:
        text: Noto Sans SC
      toggle:
        icon: material/toggle-switch
        name: Switch to White Panel
    - scheme: defualt
      primary: white
      accent: indigo
      font:
        text: Noto Serif SC
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Colored Panel

  language: zh
  favicon: assets/favicon.png
  icon:
    logo: material/cube-outline
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.share

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra:
  search:
    lang:
      - en
      - jp
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ShiinaHiiragi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ShiinaHiiragi
  generator: true
copyright: Copyright &copy; 2020 ~ 2022 Ichinoe Mizue

extra_css:
  - assets/config.css
extra_javascript:
  - assets/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - 通用:
    - 介绍: index.md
    - 许可证: intro/license.md
    - 排版规范: intro/norm.md
  - 认识基础:
    - 一、形式逻辑:
      - 1 概念: cogn/form/cep.md
      - 2 命题与演绎: cogn/form/ded.md
      - 3 归纳和类比: cogn/form/ind.md
      - 4 非形式逻辑: cogn/form/prf.md
  - 形而上学:
    - 一、认知科学:
      - 1 神经认知: meta/cogn/nerve.md
      - 2 心理认知: meta/cogn/psyc.md
      - 3 语言认知: meta/cogn/lang.md
      - 4 思维认知: meta/cogn/think.md
      - 5 文化认知: meta/cogn/civ.md
    - 三、分析哲学:
      - 1 演绎与证成: meta/logic/syntax.md
      - 2 真理与悖论: meta/logic/truth.md
      - 3 意义与指称: meta/logic/mean.md
    - 四、数学哲学:
      - 1 基本问题与历史观点: meta/math/cep.md
      - 2 三大主义: meta/math/doctr.md
      - 3 当代观点: meta/math/cont.md
  - 数理逻辑:
    - 一、结构证明论:
      - 1 命题逻辑: logic/prf/prop.md
      - 2 一阶逻辑: logic/prf/pred.md
    - 二、模型论:
      - 1 结构与模型: logic/mdl/mdl.md
    - 三、递归论:
      - 1 可计算理论: logic/rec/calc.md
      - 2 计算复杂性理论: logic/rec/cplx.md
    - 四、公理集合论:
      - 1 数学基础: logic/set/zfc.md
      - 2 序数与基数: logic/set/ordinal.md
  - 代数学:
    - 一、初等代数:
      - 1 解析式与初等函数: alg/elem/form.md
      - 2 方程与不等式: alg/elem/eq.md
      - 3 初等数论: alg/elem/num.md
      - 4 组合理论: alg/elem/comb.md
    - 二、线性代数:
      - 1 矩阵与行列式: alg/lin/mat.md
      - 2 线性空间: alg/lin/lin.md
  - 几何学:
    - 一、解析几何:
      - 1 向量与坐标系: top/anly/coord.md
    - 二、点集拓扑:
      - 1 拓扑空间: top/point/space.md
      - 2 构造空间: top/point/constr.md
      - 3 拓扑不变性质: top/point/prop.md
      - 4 图论: top/point/graph.md
  - 分析学:
    - 一、分析学原理:
      - 1 序列与级数: anly/princ/seq.md
  - 计算理论:
    - 一、形式语言:
      - 1 形式文法理论: comp/lang/gr.md
      - 4 形式语用学: comp/lang/pragma.md
