site_name: 逻辑与形而上学
site_author: 一之江
site_url: https://shiinahiiragi.github.io/note/
repo_url: https://github.com/ShiinaHiiragi/note/
repo_name: ShiinaHiiragi/note
dev_addr: 127.0.0.1:3000
theme:
  name: material
  icon:
    logo: octicons/note-24
  favicon: extra/favicon.png
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to White Panel
    - scheme: defualt
      primary: white
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Indigo Panel
  language: 'zh'

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ShiinaHiiragi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ShiinaHiiragi
  search:
    lang:
      - en
      - jp

extra_javascript:
  - extra/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - extra/config.css

nav:
  - 通用:
    - 介绍: index.md
    - 许可证: intro/license.md
    - 中转站: intro/int.md
  - 认识基础:
    - 一、认知科学:
      - 1 神经认知: cogn/cogn/nerve.md
      - 2 心理认知: cogn/cogn/psyc.md
      - 3 语言认知: cogn/cogn/lang.md
      - 4 思维认知: cogn/cogn/think.md
      - 5 文化认知: cogn/cogn/civil.md
    - 二、形式逻辑:
      - 1 概念: cogn/formal/concept.md
      - 2 命题与演绎: cogn/formal/deduction.md
      - 3 归纳和类比: cogn/formal/induction.md
      - 4 非形式逻辑: cogn/formal/proof.md
  - 形而上学:
    - 二、语言逻辑:
      - 4 形式语用学: meta/lang/pragma.md
    - 三、分析哲学:
      - 1 演绎与证成: meta/logic/syntax.md
      - 2 真理与悖论: meta/logic/truth.md
      - 3 意义与指称: meta/logic/mean.md
    - 四、数学哲学:
      - 1 基本问题与历史观点: meta/math/concept.md
      - 2 三大主义: meta/math/doctrine.md
      - 3 当代观点: meta/math/contemp.md
  - 数理逻辑:
    - 一、证明论:
      - 1 命题逻辑: logic/proof/prop.md
      - 2 一阶逻辑: logic/proof/pred.md
    - 二、模型论:
      - 1 结构与模型: logic/model/model.md
    - 四、公理集合论:
      - 1 ZFC 集合论: logic/set/zfc.md
      - 2 关系与映射: logic/set/relation.md
      - 3 实数理论: logic/set/real.md
      - 4 序数: logic/set/ordinal.md
      - 5 势与基数: logic/set/cardinal.md
  - 数学结构:
    - 一、初等代数:
      - 1 解析式: math/alg/form.md
      - 2 初等数论: math/alg/num.md
    - 二、点集拓扑:
      - 1 拓扑空间: math/top/space.md
      - 2 构造空间: math/top/construct.md
      - 3 拓扑不变性质: math/top/prop.md
