site_name: 逻辑与形而上学
site_author: 一之江
site_url: https://shiinahiiragi.github.io/note/
repo_url: https://github.com/ShiinaHiiragi/note/
repo_name: ShiinaHiiragi/note
dev_addr: 127.0.0.1:80
theme:
  name: material
  icon:
    logo: octicons/note-24
  favicon: extra/favicon.png
  features:
    - navigation.expand
    - navigation.tabs
  palette:
    accent: pink
  language: 'zh'

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ShiinaHiiragi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ShiinaHiiragi
  search:
    language: 'jp'

extra_javascript:
  - extra/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - extra/config.css

nav:
  - 通用:
      - 介绍: index.md
    #   - 索引: dir.md
      - 许可证: license.md
  - 形而上学:
      - 一、形式逻辑:
        - 1 概念: philosophy/formal/concept.md
        - 2 命题与演绎: philosophy/formal/deduction.md
        - 3 归纳和类比: philosophy/formal/induction.md
        - 4 非形式逻辑: philosophy/formal/proof.md
      - 三、数学哲学:
        - 1 基本问题与历史观点: philosophy/math/concept.md
  - 数理逻辑:
      - 二、公理集合论:
          - 1 ZFC 集合论: foundation/set/zfc.md
          - 2 关系与映射: foundation/set/relation.md
          - 3 实数理论: foundation/set/real.md
          - 4 序数: foundation/set/ordinal.md
          - 5 势与基数: foundation/set/cardinal.md
      - 三、模型论:
          - 1 结构与模型: foundation/model/model.md
          - 2 形式算术: foundation/model/arithmetic.md